version: '3'

services:
  nginx1:
    image: nginx
    container_name: nginx1
    ports:
      - 8000:80
    volumes:
      - ./volumes/html:/usr/share/nginx/html


  nginx2:
    image: nginx
    container_name: nginx2
    ports:
      - 8001:80
    volumes:
      - ./volumes/html:/usr/share/nginx/html

