version: '3'

services:
  nginx1:
    image: nginx
    container_name: nginx1
    ports:
      - 8000:80
    volumes:
      - ./volumes/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d

  nginx2:
    image: nginx
    container_name: nginx2
    ports:
      - 8001:80
    volumes:
      - ./volumes/html2:/usr/share/nginx/html
      - ./nginx/conf2:/etc/nginx/conf.d

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 8008:80
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/nginx.tmpl:/app/nginx.tmpl:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/html:/usr/share/nginx/html:rw
